### ISSUE TITLE
[Question] NSFW images?

### ISSUE THREAD

**Issue by austinhuang0131** [sairoutine/pixiv-api#1]
Thank you for your attention. I am making a chatbot for Discord, and I need to separate safe pictures and 18+ pictures. Is there a way to specify it?

**Comment by sairoutine** [comment]
Thank you for your question.
18+ pictures have "R-18" tag, so if you want to search only safe pictures, you should specify "-R-18" search criteria. It means "NOT R-18".

```
var Pixiv = require('node-pixiv');

var pixiv = new Pixiv();

pixiv.login({
    username: 'your account username',
    password: 'your account password',
})
.then(function() {
    return pixiv.search({
        q: '東方Project -R-18', // means "Touhou Project" and "NOT R-18"
        page: 1,
        per_page: 3,
        mode: 'tag',
        period: 'all',
        order: 'desc',
        sort: 'date',
        types: 'illustration,manga',
    });
})
.then(function(data) {
    console.log(data);
});
```

Thanks.

**Comment by austinhuang0131** [comment]
Thank you.
Even I closed the issue, I still have a question of range of per_page. After this question, my work will be done and I’ll share it with you (of course I’ll give you credit).

**Comment by sairoutine** [comment]
I'm very happy to be of use to you.
If you have more question, please make another issue.
Thanks.
