### ISSUE TITLE
[Question] Accessing Images

### ISSUE THREAD

**Issue by jaredallard** [sairoutine/pixiv-api#3]
Hi, I know this isn't your modules issue, but I was wondering. How do you access images returned by the `.search` method? Whenever I try to access a result from `image_urls` I get a `403 Unauthorized` returned from pixiv.

Example: https://i.pximg.net/c/150x150/img-master/img/2014/12/19/10/56/32/47627864_p0_master1200.jpg

Do you need to login to do this? If so, how?

Thank you!

**Comment by sairoutine** [comment]
You need no login, but need following referer header to access images.
```
Referer: http://www.pixiv.net/
```

**Comment by jaredallard** [comment]
Thanks! Sorry, forgot to respond to this. Closing.
